service: smartcarte

provider:
  name: aws
  runtime: python3.8
  stage: production
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::sentinel-cogs/*"
  ecr:
    images:
      appimage:
        path: ./

custom:
  apigwBinary:
    types:
      - "*/*"

plugins:
  - serverless-apigw-binary

functions:
  smart-carte:
    memorySize: 2000
    timeout: 30
    image:
      name: appimage
    events:
      - http:
          path: sentinel/{proxy+}
          method: get
          cors: true
