service: smartcarte

provider:
  name: aws
  runtime: python3.8
  memorySize: 10000
  timeout: 600
  stage: production
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::sentinel-cogs/*"
  ecr:
    images:
      appimage:
        path: ./
  environment:
    SC_AWS_KEY: asdf
    SC_AWS_SECRET: asdf

functions:
  smart-carte:
    memorySize: 2000
    timeout: 30
    image:
      name: appimage
